# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f333b6b425cf2298c0866b48e64a45aedb449d9a01cf515e5c295ed4d21401e48283d9f9d13b00e861c0c18cd36b0afdb1d2731a92273dfad073aed2b6232d20

test:
  secret_key_base: 759ec22c0e8a28572889a53071ad0ac608fb9a2a9a06814c67d6b058c2c7897541021bbe268832a0ea8ca99d22efec8bedbf2a063b9ea45dbd7fa9a00e7b0598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
